### ISSUE TITLE
[devops] improve logging for observability

### ISSUE THREAD

**Issue by davidlhw** [AfterClass-io/afterclass.io-v2#113]
## context

In the past, afterclass suffered from having user drop offs and having to deal with support issues (without much information) as there was a lack of telemetry and insights into the errors that occured. This can easily be solved by introducing observability (logs, span & metrics).

In general, Vercel has already taken care of most of the application side logging, span tracking and server metrics:

![image](https://github.com/AfterClass-io/afterclass.io-v2/assets/13061926/a9186ada-cc86-446f-ac8e-2119d08f71c0)

## task

This task is primarily focused on getting additional useful data using tools like umami and posthog.

Technically, [Umami](https://umami.is/) and [Posthog](https://posthog.com) are more or less direct competitors, with Posthog being more feature complete and Umami boasting light-weightness to their analytics code injection.

To fully understand which one is more relevant for our use case, it'll be good to give them both a try and go with the one that suits us the best.

### core

- Integrate [Umami](https://umami.is/docs/collect-data)
- Integrate [Posthog](https://posthog.com/docs/libraries/next-js)

**Comment by onebignick** [comment]
I can take up this task

**Comment by onebignick** [comment]
[Posthog]
Pros:
- Free tier currently supports 1 million api calls per month
- A lot of OOTB functionality 
- Configuration is easy
- Able to self host

Cons:
- May add unnecessary bloat to deployment
- Requires installation of posthog-js via npm, adding a dependency 

[Umami]
Pros:
- More security focused
- Lightweight
- Configurable
- Able to self-host
- Does not require a package installation

Cons:
- Will need quite a bit of configuration to reach posthog's functionality.
- Free tier supports 10k requests a month

Due to the OOTB functionality that Posthog provides, and the better free tier, advised to use posthog for now and can look at umami if circumstances change.

**Comment by davidlhw** [comment]
Thanks for the detailed analysis! :)

Aligned with you on PostHog.

Please go ahead with implementing PostHog and we'll see how that goes for us, keeping in mind that there's a possibility of abandoning it for Umami if there's too much pain involved
