### ISSUE TITLE
[Feat][UI] Format Course Details Data

### ISSUE THREAD

**Issue by Jaylin0312** [AfterClass-io/afterclass.io-v2#148]
## Mockups / Screenshots

The current  course details is not formatted as seen in the screenshot below:

![photo_2024-05-31 01 06 00](https://github.com/AfterClass-io/afterclass.io-v2/assets/68802506/3ec98c6f-04af-4471-8794-40113dbc97a9)

## Features

Instead of displaying the course details as a large block of unformatted text, the information should ideally be presented in a well-formatted and readable manner.

**Comment by davidlhw** [comment]
this issue is largely a result of how the data in obtained and stored in the db

for eg, bullet pointers are not stored as `<ol><li/><ol/>` elements, for example, but rather, just stored as `•` characters

probably not as relevant to be a ui task in this repository

we can consider manipulating data like these in the FE but there won't be a way to guarantee it is as expected. probably better to address this logic with the way data is scrapped instead

**Comment by davidlhw** [comment]
confirmed that this is a bug on the FE. the database seem to have the correct text structure

the potential fix is mentioned in #168 

![image](https://github.com/AfterClass-io/afterclass.io-v2/assets/13061926/3ee35145-8e78-4e68-a145-bc803e767353)

**Comment by Jansen52x** [comment]
I would like to work on this issue.

**Comment by Jaylin0312** [comment]
Reopen this issue as https://github.com/AfterClass-io/afterclass.io-v2/pull/174 fixed review instead of course detail

**Comment by davidlhw** [comment]
the fix for the course page is similar but at another location: [`src/modules/reviews/InformationSection/InformationCard/InformationModal.tsx#L24`](https://github.com/AfterClass-io/afterclass.io-v2/blob/main/src/modules/reviews/InformationSection/InformationCard/InformationModal.tsx#L24)

by adding a `white-space: pre-wrap;` css property to the `<Modal.Body>` like so:

```tsx
<Modal.Body className={xxx}>
```
